//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FXGuild.Common.Tracing;


namespace FXGuild.Common.Tracing.TracedTestApp.Cultivation
{
    
    internal sealed partial class Cultivator
    {
        private static Tracer CLASS_TRACER = TracerProvider.GetTracer<Cultivator>();
        private enum Task
        {
            CULTIVATE_COFFEE_BEANS,
        }
    }
}
