//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FXGuild.Common.Tracing;


namespace FXGuild.Common.UnitTests.Tracing
{
    
    internal sealed partial class GlobalTaskClass
    {
        private static Tracer CLASS_TRACER = TracerProvider.GetTracer<GlobalTaskClass>();
        private enum Task
        {
            DO_GLOBAL_STUFF,
        }
    }
}
namespace FXGuild.Common.UnitTests.Tracing.Food.Fruits
{
    
    internal sealed partial class FruitEater
    {
        private static Tracer CLASS_TRACER = TracerProvider.GetTracer<FruitEater>();
        private enum Task
        {
            EAT_FRUITS,
        }
        private enum Anomaly
        {
            FRUIT_SPECIFIC_ANOMALY,
        }
    }
}
